### ISSUE TITLE
Demo app

### ISSUE THREAD

**Issue by ajsb85** [glpi-project/swift-library-glpi#15]
Hi, @hectorerb 

Could you provide an IPA to test the GLPI API Client?

You can publish it in the TestFlight 👍 

Thanks

**Comment by hectorerb** [comment]
@ajsb85 Yes, I think it's possible to upload the example to TestFlight, but only for internal test, we can also upload github the ipa file as an artifact

**Comment by ajsb85** [comment]
@hectorerb Yes. Merci

**Comment by ajsb85** [comment]
Hi, @hectorerb 

No apps in the iTunnesConnect at the moment.
This is the vector file for the GLPI logo:

[glpi.ai.zip](https://github.com/glpi-project/swift-library-glpi/files/1418122/glpi.ai.zip)

Use Package ID related to GLPI Org.

Thanks.

**Comment by ajsb85** [comment]
Hi, @hectorerb 

I already filled the test Information on iTunes Connect.
To start testing your builds 👌
